### ISSUE TITLE
Missing "/" in waypoint_updater.py?

### ISSUE THREAD

**Issue by mischastik** [misaksson/CarND-Capstone#3]
This might be a stupid question, since I'm not really familiar with ROS so far, but why does line 37 of waypoint_updater.py read:  

      self.final_waypoints_pub = rospy.Publisher('final_waypoints', Lane, queue_size=1)

whereas everywhere else the name of a topic is preceded with "/"?

**Comment by misaksson** [comment]
Maybe the first "/" is implicit? There is also no "/" when subscribing to the topics in waypoint_follower/src/pure_pursuit.cpp line 59-63, although both /current_pose and /current_velocity are published with a starting "/", see styx/conf.py, so it seems like it doesn't matter.

**Comment by mischastik** [comment]
Ah, thanks.
